apiVersion: v1
kind: ConfigMap
metadata:
  name: adventure-configmap
  namespace: market-place-dev
data:
  application.yaml: |+
    spring:
      datasource:
        url: jdbc:postgresql://192.168.65.254:5432/market
        driver-class-name: org.postgresql.Driver
    kafka:
      server: 192.168.65.254:29092
      topics:
        market: market.test.multiple
    server:
      servlet:
        context-path: /adventure
