apiVersion: v1
kind: Service
metadata:
  name: adventure-service
  namespace: market-place-dev
  labels:
    app: adventure-label
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30007
  selector:
    app: adventure-deployment