apiVersion: apps/v1
kind: Deployment
metadata:
  name: adventure-deployment
  namespace: market-place-dev
  labels:
    app: adventure-label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adventure-deployment
  template:
    metadata:
      labels:
        app: adventure-deployment
    spec:
      hostAliases:
        - ip: 127.0.0.1
          hostnames:
            - localhost
      containers:
        - name: adventure-deployment
          image: adventure:3.4
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /adventure/actuator/health
              port: http
            failureThreshold: 3
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /adventure/actuator/health
              port: http
            failureThreshold: 3
            periodSeconds: 30
          env:
            - name: JAVA_OPTS
              value: "-Xms256m -Xmx1024m"
            - name: SPRING_CONFIG
              value: "/home/app/config/application.yaml"
            - name: TIME_ZONE
              value: "-Dlogback.timezone=Asia/Bangkok"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: adventure-secret
                  key: spring.datasource.username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: adventure-secret
                  key: spring.datasource.password
          volumeMounts:
            - name: adventure-volume
              mountPath: /home/app/config/application.yaml
              subPath: application.yaml
      volumes:
        - name: adventure-volume
          configMap:
            name: adventure-configmap